server:
  port: 8094
  servlet:
    context-path: /identity/api/v1/library

spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/library_db"
    username: root
    password: 170922Davis@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: false


jwt:
  signerKey: "GscuJW11GiHLuIhqbvA3lnnpF3q1X5q2WzgpS9eUJ+LNNoL3b31GqUoTNZCDndlS"
  valid-duration: 3600 #in seconds
  refreshable-duration: 36000 #in seconds
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    config:
      level: DEBUG
open:
    api:
        title: Library API
        description: Library API for managing books and authors
        version: 1.0.0
        serverUrl: http://localhost:8094/identity/api/v1/library
        serverName: server test
