server:
  port: 8093
  servlet:
    context-path: /identity/api/v1/library

spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/library_db"
    username: root
    password: 170922Davis@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: false


jwt:
  signerKey: "GscuJW11GiHLuIhqbvA3lnnpF3q1X5q2WzgpS9eUJ+LNNoL3b31GqUoTNZCDndlS"
